# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19cdb54e40d12f0bda56a66233af5a74502a9ebf2bd6fd9aef9ded29acbf6dac0682d406bc88c414db36219bd55a4311906451fb86904666ff87333c8647416c

test:
  secret_key_base: 8832e9aedc7b709b5c3832044f814f6ed9861079248b575b91cd33ae577c6313bebabc6ae9cf5768c5b41d610ef8bca9c13f61d507a59ca413cf92aab26c1d41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
